name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Gems
      run: |
        gem install bundler
        bundle install
        
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.app

    - name: Build and test
      run: |
        set -o pipefail
        xcodebuild clean build test \
        -scheme SuperAPP \
        -destination 'platform=iOS Simulator,name=iPhone 11 Pro' \
        | xcpretty
