name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    xcode:
        name: Xcode
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set Gems
              run: |
                gem install bundler
                bundle install
                
            - name: Select Xcode
              run: sudo xcode-select -switch /Applications/Xcode_12.app

            - name: Build and test
              run: |
                set -o pipefail
                slather setup
                xcodebuild clean build test \
                -scheme SuperAPP \
                -destination 'platform=iOS Simulator,name=iPhone 11 Pro' \
                -enableCodeCoverage YES \
                | xcpretty
            
            - name: Coverage report
              run: slather coverage -x --binary-basename 'SuperAPP'

            - name: Post coverage
              uses: codecov/codecov-action@v1
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                file: ./Coverage/cobertura.xml
                fail_ci_if_error: true   

    danger:
        name: Danger
        runs-on: ubuntu-latest
        steps:
        - name: Set up Ruby 2.6.3
          uses: actions/setup-ruby@v1
          with:
            ruby-version: '2.6'
        - name: Bundle install
          run: |
            gem install bundler
            bundle config path vendor/bundle
            bundle install --jobs 4 --retry 3
        - name: Run danger
          run: |
            bundle exec danger
          env:
            DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
