name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    xcode:
        name: Xcode
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set Gems
              run: |
                ruby --version
                gem --version
                bundler --version

            - name: cache gems
              uses: actions/cache@v1
              with:
                path: vendor/bundle
                key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
                restore-keys: |
                  ${{ runner.os }}-gem-

            - name: bundle install
              run: |
                bundle config path vendor/bundle
                bundle install --without=documentation --jobs 4 --retry 3
                        
            - name: Danger
              env:
                DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
              run: bundle exec danger

            - name: Select Xcode
              run: sudo xcode-select -switch /Applications/Xcode_12.app

            - name: Build and test
              run: |
                set -o pipefail
                slather setup
                xcodebuild clean build test \
                -scheme SuperAPP \
                -destination 'platform=iOS Simulator,name=iPhone 11 Pro' \
                -enableCodeCoverage YES \
                | xcpretty
            
            - name: Coverage report
              run: slather coverage -x --binary-basename 'SuperAPP'

            - name: Post coverage
              uses: codecov/codecov-action@v1
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                file: ./Coverage/cobertura.xml
                fail_ci_if_error: true
