name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Gems
      run: |
        gem install bundler
        bundle install
        
    - name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: 12.1
        
    - name: Build
      run: |
        set -o pipefail
        xcodebuild build \
        -scheme SuperAPP \
        -destination 'platform=iOS Simulator,name=iPhone 11 Pro' \
        | xcpretty
